##**[10주차]실습**
- 아래의 실습1), 실습2), 실습3)를 수행하시오.


In [7]:
print("2353881, 최대영")

2353881, 최대영


In [8]:
from google.colab import auth

auth.authenticate_user()
!gcloud config get-value account

tigers7101@gmail.com


In [9]:
!pip install nltk

###**예제 1) 자연어 처리를 위한 텍스트 전처리를 수행한다.**
- **[실습목표]** 자연어를 학습에 활용하기 적절한 형테로 텍스트에 전처리를 적용한다.

####**실습 1-1)**
  - 입력 텍스트를 단어 단위로 쪼개 토큰화 하고, 리스트로 만든다.
  - 리스트에서 구두점은 제외 된다.

In [10]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt_tab')

tokens = word_tokenize("Hello World, This is a dog.")

# 문자나 숫자인 경우에만 단어를 리스트에 추가한다.
words = [word for word in tokens if word.isalpha()]
print(words)

['Hello', 'World', 'This', 'is', 'a', 'dog']


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


####**실습 1-2)**
  - 라이브러리(NLRK, kears)를 이용하여 텍스트를 토큰으로 처리해본다.
  - 토큰은 단어 단위, 혹은 문장 단위로 나눌 수 있다.

In [11]:
# NLRK 라이브러리를 활용한 토큰화 1
import nltk
from nltk.tokenize import word_tokenize

text = "This is a dog."
print(word_tokenize(text))

['This', 'is', 'a', 'dog', '.']


In [12]:
# NLRK 라이브러리를 활용한 토큰화 2
from nltk.tokenize import sent_tokenize

text = "Hello World!, This is a dog."
print(sent_tokenize(text))

['Hello World!, This is a dog.']


In [13]:
# keras 라이브러리를 활용한 토큰화
from tensorflow.keras.preprocessing.text import *

print(text_to_word_sequence("This is a dog."))

['this', 'is', 'a', 'dog']


####**실습 1-3)**
  - 신경망에서 단어를 처리하기 위해, 단어를 숫자 데이터로 표현하는 방식에는 정수 인코딩, 원-핫 인코딩, 워드 임베딩 방법이 포함된다.
  - 본 실습에서는 keras 라이브러리를 활용하여 원-핫 인코딩을 수행해본다.

In [14]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# 변환하고 싶은 단어 리스트를 정의
text = ["cat", "dog", "cat", "bird"]

# 단어 임베딩을 위한 단어 집합
total_pets = ["cat", "dog", "turtle", "fish", "bird"]

print("text=", text)

text= ['cat', 'dog', 'cat', 'bird']


In [15]:
# 변환에 사용되는 딕셔너리를 정의

'''여기에 코드를 작성하시오'''
mapping = {}
for x in range(len(total_pets)):
  mapping[total_pets[x]] = x
'''여기에 코드를 작성하시오'''	#“cat"->0, "dog"->1, ...
print(mapping)

{'cat': 0, 'dog': 1, 'turtle': 2, 'fish': 3, 'bird': 4}


In [16]:
# 변환 하고자 했던 단어 리스트를 순차적인 정수 인덱스로 변환

for x in range(len(text)):
  text[x] = mapping[text[x]]

print("text=", text)

text= [0, 1, 0, 4]


In [17]:
# 앞서 정수 인덱스로 변환한 text의 값을 원-핫 인코딩으로 표현
one_hot_encode = to_categorical(text)
print("text=", one_hot_encode)

text= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


####**실습 1-4)**
  - 케라스 라이브러리에서 지원하는 자연어 처리를 위한 전처리 함수에 대해 실습해본다.


In [18]:
# 입력 자연어 문장에 대해 토큰화 수행
from tensorflow.keras.preprocessing.text import Tokenizer

'''여기에 코드를 작성하시오'''

t = Tokenizer()
text = """Deep learning is part of a broder family of machine learning methods based on artificial neural networks with representation learning."""

t.fit_on_texts([text])
print("단어집합 : ", t.word_index)

# 입력 문장에 대한 정수 인코딩 결과 출력
seq = t.texts_to_sequences([text])[0]
print(text, "->", seq)


단어집합 :  {'learning': 1, 'of': 2, 'deep': 3, 'is': 4, 'part': 5, 'a': 6, 'broder': 7, 'family': 8, 'machine': 9, 'methods': 10, 'based': 11, 'on': 12, 'artificial': 13, 'neural': 14, 'networks': 15, 'with': 16, 'representation': 17}
Deep learning is part of a broder family of machine learning methods based on artificial neural networks with representation learning. -> [3, 1, 4, 5, 2, 6, 7, 8, 2, 9, 1, 10, 11, 12, 13, 14, 15, 16, 17, 1]


In [19]:
# 샘플의 패딩
from tensorflow.keras.preprocessing.sequence import pad_sequences
X = pad_sequences([[7, 8, 9], [1, 2, 3, 4, 5], [7]], maxlen=3, padding='pre')
print(X)

[[7 8 9]
 [3 4 5]
 [0 0 7]]


In [20]:
# keras의 Embedding 레이어 활용 실습
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

# 입력 형태: (batch_size, input_length)=(32, 3)
# 출력 형태: (None, 3, 4)
model = Sequential()
model.add(Embedding(100, 4, input_length=3))

input_array = np.random.randint(100, size=(32, 3))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
print(output_array.shape)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 404ms/step
(32, 3, 4)


###**예제 2) 스팸 메일 분류하기**
- **[실습목표]** 자연어를 인식하여, 메일의 스팸 메일 여부를 판별하는 모델을 학습한다.


In [21]:
# 필요 라이브러리 import
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [22]:
# 훈련 데이터셋을 정의
docs = [	'additional income',
		'best price',
		'big bucks',
		'cash bonus',
		'earn extra cash',
		'spring savings certificate',
		'valero gas marketing',
		'all domestic employees',
		'nominations for oct',
		'confirmation from spinner']

# 훈련 데이터의 정답 레이블
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [23]:
# keras의 텍스트 전처리 함수를 사용하여 정수 인코딩 수행
# 각 입력 문장에 포함되는 단어들에 대한 정수 인코딩 정보가 encoded_docs에 저장됨
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[34, 48], [34, 48], [18, 12], [9, 30], [10, 29, 9], [43, 45, 25], [3, 13, 19], [5, 4, 29], [20, 18, 43], [1, 31, 33]]


In [24]:
# 모든 입력 정수 인코딩 결과의 길이를 맞추기 위해 max_length에 맞게 padding을 적용
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding = 'post')
print(padded_docs)

[[34 48  0  0]
 [34 48  0  0]
 [18 12  0  0]
 [ 9 30  0  0]
 [10 29  9  0]
 [43 45 25  0]
 [ 3 13 19  0]
 [ 5  4 29  0]
 [20 18 43  0]
 [ 1 31 33  0]]


In [25]:
# 정수 인코딩 결과를 기반으로 자연어 처리 모델 학습을 수행하기 위해 모델을 정의
# 모델에는 Embedding(단어 임베딩), Flatten, Dense 레이어를 포함

model = Sequential()
'''여기에 코드를 작성하시오'''
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(padded_docs, labels, epochs=50, verbose=0)

In [26]:
# 학습으로 사용한 데이터를 기반으로 모델의 학습 정확도를 측정
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도=', accuracy)

# test_doc을 입력받아, 해당 문장이 스팸인지 판별을 수행
# test_doc의 정보 또한 모델에 입력 전에 정수 인코딩이 필요
test_doc = ['big income']
'''여기에 코드를 작성하시오'''
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding = 'post')

print(model.predict(padded_docs))

정확도= 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
[[0.5810253]]


###**예제 3) 다음 단어 예측하기**
- **[실습목표]** 문장을 입력받고, 그 다음에 이어질 단어를 예측하는 모델을 구축한다.


In [27]:
# 필요 라이브러리 정의
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [28]:
# 테스트 데이터 정의
text_data="""Soft as the voice of an angel\n
Breathing a lesson unhead\n
Hope with a gentle persuasion\n
Whispers her comforting word\n
Wait till the darkness is over\n
Wait till the tempest is done\n
Hope for sunshine tomorrow\n
After the shower
"""

In [29]:
# keras 라이브러리의 토큰화 함수를 사용하여 데이터 전처리 수행
'''여기에 코드를 작성하시오'''
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text_data])
encoded = tokenizer.texts_to_sequences([text_data])[0]
print(encoded)
print(tokenizer.word_index)

vocab_size = len(tokenizer.word_index) + 1
print('어휘 크기: %d\n' % vocab_size)

[7, 8, 1, 9, 10, 11, 12, 13, 2, 14, 15, 3, 16, 2, 17, 18, 19, 20, 21, 22, 4, 5, 1, 23, 6, 24, 4, 5, 1, 25, 6, 26, 3, 27, 28, 29, 30, 1, 31]
{'the': 1, 'a': 2, 'hope': 3, 'wait': 4, 'till': 5, 'is': 6, 'soft': 7, 'as': 8, 'voice': 9, 'of': 10, 'an': 11, 'angel': 12, 'breathing': 13, 'lesson': 14, 'unhead': 15, 'with': 16, 'gentle': 17, 'persuasion': 18, 'whispers': 19, 'her': 20, 'comforting': 21, 'word': 22, 'darkness': 23, 'over': 24, 'tempest': 25, 'done': 26, 'for': 27, 'sunshine': 28, 'tomorrow': 29, 'after': 30, 'shower': 31}
어휘 크기: 32



In [30]:
# 훈련 데이터세트 문장을 쪼개서, 순차 데이터를 생성

'''여기에 코드를 작성하시오'''
sequences = list()
for i in range(1, len(encoded)):
  sequence = encoded[i-1:i+1]
  sequences.append(sequence)

print(sequences)
print('총 시퀀스 개수: %d' % len(sequences))

[[7, 8], [8, 1], [1, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 2], [2, 14], [14, 15], [15, 3], [3, 16], [16, 2], [2, 17], [17, 18], [18, 19], [19, 20], [20, 21], [21, 22], [22, 4], [4, 5], [5, 1], [1, 23], [23, 6], [6, 24], [24, 4], [4, 5], [5, 1], [1, 25], [25, 6], [6, 26], [26, 3], [3, 27], [27, 28], [28, 29], [29, 30], [30, 1], [1, 31]]
총 시퀀스 개수: 38


In [31]:
# 생성한 순차 데이터를 기반으로 학습데이터와 정답 라벨을 분리

'''여기에 코드를 작성하시오'''
sequences = np.array(sequences)
X, y = sequences[:,0], sequences[:, 1]
print("X=", X)
print("y=", y)

X= [ 7  8  1  9 10 11 12 13  2 14 15  3 16  2 17 18 19 20 21 22  4  5  1 23
  6 24  4  5  1 25  6 26  3 27 28 29 30  1]
y= [ 8  1  9 10 11 12 13  2 14 15  3 16  2 17 18 19 20 21 22  4  5  1 23  6
 24  4  5  1 25  6 26  3 27 28 29 30  1 31]


In [32]:
# 순차 데이터 학습을 위한 모델을 정의하고 학습을 수행
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM, Reshape

# 모델 정의, 교재의 Embbedding 레이어와 LSTM 레이어 사이에 Reshape((1, 10))레이어 추가 필요

'''여기에 코드를 작성하시오'''
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(Reshape((1, 10)))
model.add(LSTM(32))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()
print(X.shape)
model.fit(X, y, epochs=500, verbose=2)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

(38,)
Epoch 1/500
2/2 - 3s - 1s/step - accuracy: 0.0526 - loss: 3.4656
Epoch 2/500
2/2 - 0s - 25ms/step - accuracy: 0.0526 - loss: 3.4643
Epoch 3/500
2/2 - 0s - 24ms/step - accuracy: 0.0789 - loss: 3.4634
Epoch 4/500
2/2 - 0s - 24ms/step - accuracy: 0.1316 - loss: 3.4626
Epoch 5/500
2/2 - 0s - 25ms/step - accuracy: 0.1579 - loss: 3.4616
Epoch 6/500
2/2 - 0s - 30ms/step - accuracy: 0.1316 - loss: 3.4607
Epoch 7/500
2/2 - 0s - 32ms/step - accuracy: 0.1842 - loss: 3.4599
Epoch 8/500
2/2 - 0s - 27ms/step - accuracy: 0.1842 - loss: 3.4590
Epoch 9/500
2/2 - 0s - 28ms/step - accuracy: 0.1842 - loss: 3.4581
Epoch 10/500
2/2 - 0s - 33ms/step - accuracy: 0.1842 - loss: 3.4573
Epoch 11/500
2/2 - 0s - 34ms/step - accuracy: 0.1842 - loss: 3.4564
Epoch 12/500
2/2 - 0s - 52ms/step - accuracy: 0.1579 - loss: 3.4554
Epoch 13/500
2/2 - 0s - 67ms/step - accuracy: 0.1579 - loss: 3.4545
Epoch 14/500
2/2 - 0s - 41ms/step - accuracy: 0.1579 - loss: 3.4535
Epoch 15/500
2/2 - 0s - 41ms/step - accuracy: 0.1579 

In [33]:
# 학습한 순차 신경망 테스트를 수행
# 테스트 단어를 정수 인코딩한다.
test_text = 'Wait'

'''여기에 코드를 작성하시오'''
encoded = tokenizer.texts_to_sequences([test_text])[0]
encoded = np.array(encoded)
# 신경망의 예측값을 출력해본다.
onehot_output = model.predict(encoded)
print('onehot_output=', onehot_output)

# 가장 높은 출력을 내는 유닛을 찾는다.
output = np.argmax(onehot_output)
print('output=', output)

# 출력층의 유닛 번호를 단어로 바꾼다.
print(test_text, "=>", end=" ")
'''여기에 코드를 작성하시오'''
for word, index in tokenizer.word_index.items():
  if index == output:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step
onehot_output= [[1.0296531e-04 2.0997240e-05 7.0341742e-03 7.9978323e-03 1.8046545e-03
  9.5559680e-01 1.0994500e-02 7.8540725e-05 8.3952438e-07 2.0195573e-06
  1.2016032e-02 1.6956885e-06 1.8481916e-06 6.6919762e-05 1.2836428e-04
  5.4970582e-04 2.7018414e-05 1.5772806e-04 1.9458964e-03 3.1172132e-04
  6.5171567e-05 8.8268582e-04 5.7418920e-06 1.2338385e-06 4.2787965e-06
  1.7320211e-06 5.3486083e-06 3.0349329e-05 3.9262817e-05 8.5686461e-06
  1.1429232e-04 1.0424063e-06]]
output= 5
Wait => till
